---
title: "Week 6: Discussion Section"
author: "Josephine Cardelle"
format: html
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(tmaptools)
```

```{r}
# Set directory for folder
pre_fire_dir <- here::here("data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
# Set directory for folder
post_fire_dir <- here::here("data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
nbr_fun <- function(nir, swir2){
    (nir - swir2)/(nir + swir2)
}
```

```{r}
# Rename the bands of the pre_fire and post_fire raster
bands <- c("Aerosol", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2")
names(pre_fire_rast) <- bands
names(post_fire_rast) <- bands
```


```{r}
# Mask out clouds and shadows with the pre_mask and post_mask rasters
pre_mask[pre_mask > 0] <- NA
post_mask[post_mask > 0] <- NA 


pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)
post_fire_rast <- mask(post_fire_rast, mask = post_mask)

# View raster
plot(pre_fire_rast, colNA = "white")
plot(post_fire_rast, colNA = "white")
```

# Plot true color composite
```{r}
plotRGB(pre_fire_rast, r = 4, g = 3, b = 2, stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 4, g = 3, b = 2, stretch = "lin", colNA = "black")
```

# Plot false color composite
```{r}
plotRGB(pre_fire_rast, r = 7, g = 5, b = 3, stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 7, g = 5, b = 3, stretch = "lin", colNA = "black")
```

# Calculate NBR and dNBR
```{r}
pre_nbr_rast <- terra::lapp(pre_fire_rast[[c(5, 7)]], fun = nbr_fun)

plot(pre_nbr_rast, main = "Cold Springs Pre-Fire NBR", colNA = "black")
```

```{r}
post_nbr_rast <- terra::lapp(post_fire_rast[[c(5, 7)]], fun = nbr_fun)

plot(post_nbr_rast, main = "Cold Springs Post-Fire NBR", colNA = "black")
```

# Calculate and Plot dNBR
```{r}
diff_nbr <- pre_nbr_rast - post_nbr_rast

tm_shape(diff_nbr) +
  tm_raster(style = "equal", n = 6, 
            palette = get_brewer_pal("YlOrRd", n = 6, plot = FALSE),
            title = "Difference NBR (dNBR)", colorNA = "black") +
  tm_layout(legend.outside = TRUE)
```

